[package]
name = "test-opr-leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.2" # leptos still uses that old one
leptonic = { version = "0.3.0", features = ["csr"] }
# leptonic does not like leptos' "nightly"
leptos = { version = "0.5.5", features = ["csr"] }

[dependencies.opr]
git = "https://github.com/ydirson/opr-rs"
#path = "../opr-rs"

[build-dependencies]
leptonic-theme = "0.3.0"
