[package]
name = "generals-familiar"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.2" # leptos still uses that old one
leptonic = { version = "0.5.0", features = ["csr"] }
# leptonic does not like leptos' "nightly"
leptos = { version = "0.6.5", default-features = false, features = ["csr"] }

[dependencies.opr]
git = "https://github.com/ydirson/opr-rs"
rev = "5ad81d96d8e28fa9e4840041f2a810b9b78a2fe2"
#path = "../opr-rs"

[package.metadata.leptonic]
# REQUIRED: Leptonic's build-script will copy the Leptonic themes to this directory. Relative to your project root.
style-dir = "style"

# REQUIRED: Leptonic's build-script will copy static JS dependencies to this directory. Relative to your project root.
# Leptonic's `<Root>` component expects JS files to be available at a "js" directory at runtime (for dynamic script includes). Specify a different prop value if you choose a non-stadard location here. 
js-dir = "public/js"